Add LVar extrapolation flag
kkondo1981/aglm pull request #53
Opened 2021-02-07 14:40 UTC by kazuzowo

2021-02-11 02:00 UTC, kkondo1981 requested changes
Thanks and please check review comments on each file.

2021-02-11 02:00 UTC, kkondo1981 commented on DESCRIPTION
> +    MASS
LGTM because packages used in examples should be listed in suggests, as below:

https://cran.r-project.org/doc/manuals/r-release/R-exts.html
> The ‘Suggests’ field uses the same syntax as ‘Depends’ and lists packages that are not necessarily needed. This includes packages used only in examples, tests or vignettes (see Writing package vignettes), and packages loaded in the body of functions. E.g., suppose an example11 from package foo uses a dataset from package bar. Then it is not necessary to have bar use foo unless one wants to execute all the examples/tests/vignettes: it is useful to have bar, but not necessary. Version requirements can be specified but should be checked by the code which uses the package.

2021-02-11 02:00 UTC, kkondo1981 commented on R/aglm-input.R
> +                     LVar_extrapolation_flat=FALSE,
Wondering if there could be only two extrapolation methods?
If so,  switching with a boolean flag is OK.
Otherwise, switching with string labels such as LVar_extrapolation_method='flat' seems more suitable.

2021-02-11 02:00 UTC, kkondo1981 commented on R/get-dummies.R
> +    dummy_mat <- abs(pmax(pmin(X,max(B0)),min(B0)) - B0)
- Seems slightly difficult. Guessing it's same as preprocessing `x_vec` before making X,  as `x_vec <- pmax(pmin(x_vec, UB), LB)` ? If so, it's more readable and better because we can use common codes for making `dummy_mat`.
- Spaces after commas are welcomed.

2021-02-11 02:00 UTC, kkondo1981 commented on R/get-dummies.R
> +    dummy_mat[,c(1,ncol)] <- (X- B0)[,c(1,ncol)]
- I'm not sure why the first and the last columns of  `dummy_mat` should be canged...
- Spaces after commas are welcomed.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +##
Is this multiple-line comment used as a section title?
If so, please put another title for the former part.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +f <- function(x){x ^ 3 - 6 * x ^ 2 + 12 * x}
Please remove spaces around `^`.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +#plot(x, y)
Please remove this line.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +xy <- as.data.frame(cbind(x = x, y = y))
Same as `data.frame(x = x, y = y)` ?

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +xy_test <- as.data.frame(cbind(x = x_test, y = y_test))
Same as data.frame(x = x,_test y = y_test) ?

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +set.seed(SEED)
What's the purpose of this line?

2021-02-11 02:00 UTC, kkondo1981 commented on DESCRIPTION
> +    MASS
If so, I guess that the  `Metrics` package should be added here.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +(rmse_default <- Metrics::rmse(y_test, pred))
Why is this line parenthesized?

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +(rmse_flat <- Metrics::rmse(y_test, pred))
Why is this line parenthesized?

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +plot(model, s = model@lambda.min, layout = c(1, 1))
I'm slightly confused when running, because so many similar plots are drawn.
So, how about setting title for this plot?

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +plot(model, s = model@lambda.min, layout = c(1, 1))
Same as above.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +set.seed(SEED)
Same as above.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +set.seed(SEED)
Same as above.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +(rmse_OD <- Metrics::rmse(y_test, pred))
Same as above.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +plot(model, s = model@lambda.min, layout = c(1, 1))
Same as above.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +(rmse_gam <- Metrics::rmse(y_test, pred))
Same as above.

2021-02-11 02:00 UTC, kkondo1981 commented on examples/LVar.R
> +  rmse_gam = rmse_gam)
These 4 lines seem useless.

2021-02-18 15:15 UTC, kazuzowo commented on DESCRIPTION
> +    MASS
no longer use Metrics package for example

2021-02-18 22:46 UTC, kkondo1981 commented
Thanks for improvement but I'm slightly unsatisfied with this PR, so will merge it into a subbranch and make some fixes by myself.

2021-02-18 22:47 UTC, merged